"""
Generate baseline comparisons for the AMP-CS defense slides.

This script intentionally keeps dependencies light (NumPy + Pillow) so it can run
on the same machine as the demo without pulling external GitHub projects.

Baselines:
- Noise-cipher baseline: simulates the visual appearance of conventional image
  ciphertext. It is used to compare "ciphertext visibility", not cryptographic
  strength.
- LSB steganography baseline: hides the first target image in the least
  significant bits of the carrier. It is used to compare carrier imperceptibility
  and capacity/permission limitations.
- AMP-CS output: uses artifacts generated by run_demo_experiments.py.
"""

import argparse
import csv
import math
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageOps


ROOT = Path(__file__).resolve().parent


def load_rgb(path: Path) -> np.ndarray:
    return np.array(Image.open(path).convert("RGB"), dtype=np.uint8)


def load_gray(path: Path) -> np.ndarray:
    return np.array(Image.open(path).convert("L"), dtype=np.uint8)


def save_rgb(path: Path, arr: np.ndarray) -> None:
    Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8)).save(path)


def psnr(a: np.ndarray, b: np.ndarray) -> float:
    a = a.astype(np.float64)
    b = b.astype(np.float64)
    mse = np.mean((a - b) ** 2)
    if mse == 0:
        return float("inf")
    return 10 * math.log10((255.0 * 255.0) / mse)


def simple_ssim(a: np.ndarray, b: np.ndarray) -> float:
    a = a.astype(np.float64)
    b = b.astype(np.float64)
    if a.ndim == 3:
        return float(np.mean([simple_ssim(a[:, :, i], b[:, :, i]) for i in range(a.shape[2])]))
    c1 = (0.01 * 255) ** 2
    c2 = (0.03 * 255) ** 2
    mu_a = np.mean(a)
    mu_b = np.mean(b)
    var_a = np.var(a)
    var_b = np.var(b)
    cov = np.mean((a - mu_a) * (b - mu_b))
    return float(((2 * mu_a * mu_b + c1) * (2 * cov + c2)) / ((mu_a**2 + mu_b**2 + c1) * (var_a + var_b + c2)))


def entropy(arr: np.ndarray) -> float:
    values, counts = np.unique(arr.astype(np.uint8), return_counts=True)
    probs = counts.astype(np.float64) / counts.sum()
    return float(-np.sum(probs * np.log2(probs + 1e-12)))


def noise_cipher_like(reference: np.ndarray, seed: int = 20260524) -> np.ndarray:
    rng = np.random.default_rng(seed)
    return rng.integers(0, 256, size=reference.shape, dtype=np.uint8)


def lsb_embed(carrier_rgb: np.ndarray, secret_gray: np.ndarray) -> tuple[np.ndarray, int]:
    h = min(carrier_rgb.shape[0], secret_gray.shape[0])
    w = min(carrier_rgb.shape[1], secret_gray.shape[1])
    stego = carrier_rgb.copy()
    secret = secret_gray[:h, :w]
    bits = np.unpackbits(secret.reshape(-1, 1), axis=1)
    flat = stego[:h, :w, :].reshape(-1)
    capacity = flat.size
    payload = bits.reshape(-1)
    usable = min(capacity, payload.size)
    flat[:usable] = (flat[:usable] & 0xFE) | payload[:usable]
    stego[:h, :w, :] = flat.reshape(h, w, 3)
    return stego, usable


def lsb_extract(stego_rgb: np.ndarray, height: int, width: int) -> np.ndarray:
    h = min(stego_rgb.shape[0], height)
    w = min(stego_rgb.shape[1], width)
    bit_count = h * w * 8
    bits = (stego_rgb[:h, :w, :].reshape(-1) & 1)[:bit_count]
    if bits.size < bit_count:
        bits = np.pad(bits, (0, bit_count - bits.size))
    return np.packbits(bits.reshape(-1, 8), axis=1).reshape(h, w).astype(np.uint8)


def find_font(size: int):
    for candidate in ["C:/Windows/Fonts/msyh.ttc", "C:/Windows/Fonts/simhei.ttf", "C:/Windows/Fonts/arial.ttf"]:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def tile(path: Path, title: str, subtitle: str, size=(340, 260)) -> Image.Image:
    card_w, card_h = size
    canvas = Image.new("RGB", size, "#111827")
    draw = ImageDraw.Draw(canvas)
    draw.rounded_rectangle([0, 0, card_w - 1, card_h - 1], radius=14, outline="#334155", width=2, fill="#111827")
    img = Image.open(path).convert("RGB")
    preview = ImageOps.contain(img, (card_w - 42, card_h - 86), method=Image.Resampling.LANCZOS)
    canvas.paste(preview, ((card_w - preview.width) // 2, 62 + (card_h - 90 - preview.height) // 2))
    draw.text((18, 14), title, fill="#f8fafc", font=find_font(18))
    draw.text((18, 38), subtitle, fill="#9cc6e8", font=find_font(13))
    return canvas


def make_grid(output_dir: Path, items: list[tuple[str, str, Path]]) -> None:
    gap = 18
    cols = 3
    rows = math.ceil(len(items) / cols)
    grid_w = cols * 340 + (cols + 1) * gap
    grid_h = rows * 260 + (rows + 1) * gap + 42
    grid = Image.new("RGB", (grid_w, grid_h), "#0b1118")
    draw = ImageDraw.Draw(grid)
    draw.text((gap, 14), "Baseline Comparison: Ciphertext / LSB / AMP-CS", fill="#f8fafc", font=find_font(24))
    for idx, (title, subtitle, path) in enumerate(items):
        row, col = divmod(idx, cols)
        grid.paste(tile(path, title, subtitle), (gap + col * (340 + gap), 60 + row * (260 + gap)))
    grid.save(output_dir / "baseline_comparison_grid.png")


def write_rows(output_dir: Path, rows: list[dict]) -> None:
    fields = ["method", "comparison_role", "carrier_psnr", "carrier_ssim", "recovery_psnr", "recovery_ssim", "entropy", "notes"]
    with (output_dir / "baseline_comparison.csv").open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    with (output_dir / "baseline_comparison.md").open("w", encoding="utf-8") as f:
        f.write("| Method | Role | Carrier PSNR/SSIM | Recovery PSNR/SSIM | Entropy | Notes |\n")
        f.write("|---|---|---:|---:|---:|---|\n")
        for r in rows:
            f.write(
                f"| {r['method']} | {r['comparison_role']} | {r['carrier_psnr']} / {r['carrier_ssim']} | "
                f"{r['recovery_psnr']} / {r['recovery_ssim']} | {r['entropy']} | {r['notes']} |\n"
            )


def run(input_dir: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    carrier = load_rgb(input_dir / "10_carrier_original.png")
    ampcs_stego = load_rgb(input_dir / "11_carrier_steganographic.png")
    target = load_gray(input_dir / "04_target_image_1.png")
    ampcs_recovered = load_gray(input_dir / "recovered_B_target_1.png")
    wrong_key = load_gray(input_dir / "wrong_key_target_1.png")

    noise = noise_cipher_like(target)
    noise_rgb = np.repeat(noise[:, :, None], 3, axis=2)
    save_rgb(output_dir / "baseline_noise_cipher.png", noise_rgb)

    lsb_stego, lsb_bits = lsb_embed(carrier, target)
    lsb_recovered = lsb_extract(lsb_stego, target.shape[0], target.shape[1])
    save_rgb(output_dir / "baseline_lsb_stego.png", lsb_stego)
    Image.fromarray(lsb_recovered).save(output_dir / "baseline_lsb_recovered.png")

    save_rgb(output_dir / "ampcs_stego.png", ampcs_stego)
    Image.fromarray(ampcs_recovered).save(output_dir / "ampcs_recovered_target.png")
    Image.fromarray(wrong_key).save(output_dir / "ampcs_wrong_key.png")

    rows = [
        {
            "method": "Noise-cipher baseline",
            "comparison_role": "traditional ciphertext appearance",
            "carrier_psnr": "-",
            "carrier_ssim": "-",
            "recovery_psnr": f"{psnr(target, noise):.2f}",
            "recovery_ssim": f"{simple_ssim(target, noise):.4f}",
            "entropy": f"{entropy(noise):.2f}",
            "notes": "Shows why visible ciphertext attracts attention; not a cryptographic-strength comparison.",
        },
        {
            "method": "LSB steganography baseline",
            "comparison_role": "ordinary single-image steganography",
            "carrier_psnr": f"{psnr(carrier, lsb_stego):.2f}",
            "carrier_ssim": f"{simple_ssim(carrier, lsb_stego):.4f}",
            "recovery_psnr": f"{psnr(target, lsb_recovered):.2f}",
            "recovery_ssim": f"{simple_ssim(target, lsb_recovered):.4f}",
            "entropy": f"{entropy(lsb_stego):.2f}",
            "notes": f"Hides one target image using {lsb_bits} LSB payload bits; no multi-level permission design.",
        },
        {
            "method": "AMP-CS system",
            "comparison_role": "compressed measurement + DCT stego + role recovery",
            "carrier_psnr": f"{psnr(carrier, ampcs_stego):.2f}",
            "carrier_ssim": f"{simple_ssim(carrier, ampcs_stego):.4f}",
            "recovery_psnr": f"{psnr(target, ampcs_recovered):.2f}",
            "recovery_ssim": f"{simple_ssim(target, ampcs_recovered):.4f}",
            "entropy": f"{entropy(ampcs_stego):.2f}",
            "notes": "Supports carrier preview, target/source recovery, and wrong-key failure.",
        },
        {
            "method": "AMP-CS wrong-key ablation",
            "comparison_role": "key sensitivity",
            "carrier_psnr": "-",
            "carrier_ssim": "-",
            "recovery_psnr": f"{psnr(target, wrong_key):.2f}",
            "recovery_ssim": f"{simple_ssim(target, wrong_key):.4f}",
            "entropy": f"{entropy(wrong_key):.2f}",
            "notes": "Wrong scrambling index fails to recover valid target image.",
        },
    ]
    write_rows(output_dir, rows)

    make_grid(
        output_dir,
        [
            ("Original carrier", "public-looking image", input_dir / "10_carrier_original.png"),
            ("Noise cipher baseline", "visible ciphertext appearance", output_dir / "baseline_noise_cipher.png"),
            ("LSB stego baseline", "ordinary steganography", output_dir / "baseline_lsb_stego.png"),
            ("AMP-CS output", "compressed measurement stego", output_dir / "ampcs_stego.png"),
            ("AMP-CS recovery", "correct key restores target", output_dir / "ampcs_recovered_target.png"),
            ("Wrong-key recovery", "key/index error fails", output_dir / "ampcs_wrong_key.png"),
        ],
    )
    print(f"Saved baseline artifacts to: {output_dir}")
    print(output_dir / "baseline_comparison_grid.png")
    print(output_dir / "baseline_comparison.csv")
    print(output_dir / "baseline_comparison.md")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate baseline comparison artifacts.")
    parser.add_argument("--input-dir", default=str(ROOT / "output" / "demo_experiments"))
    parser.add_argument("--output-dir", default=str(ROOT / "output" / "baseline_comparison"))
    args = parser.parse_args()
    run(Path(args.input_dir).resolve(), Path(args.output_dir).resolve())


if __name__ == "__main__":
    main()
