"""
Generate baseline comparisons for the AMP-CS defense slides.

This script intentionally keeps dependencies light (NumPy + Pillow) so it can run
on the same machine as the demo without pulling external GitHub projects.

Baselines:
- Noise-cipher baseline: simulates the visual appearance of conventional image
  ciphertext. It is used to compare "ciphertext visibility", not cryptographic
  strength.
- LSB steganography baseline: hides each target image in the least significant
  bits of the same carrier, then reports the mean metrics. It is used to compare
  carrier imperceptibility and capacity/permission limitations.
- AMP-CS output: uses artifacts generated by run_demo_experiments.py.
"""

import argparse
import csv
import math
from pathlib import Path
from statistics import mean

import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageOps


ROOT = Path(__file__).resolve().parent


def load_rgb(path: Path) -> np.ndarray:
    return np.array(Image.open(path).convert("RGB"), dtype=np.uint8)


def load_gray(path: Path) -> np.ndarray:
    return np.array(Image.open(path).convert("L"), dtype=np.uint8)


def save_rgb(path: Path, arr: np.ndarray) -> None:
    Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8)).save(path)


def psnr(a: np.ndarray, b: np.ndarray) -> float:
    a = a.astype(np.float64)
    b = b.astype(np.float64)
    mse = np.mean((a - b) ** 2)
    if mse == 0:
        return float("inf")
    return 10 * math.log10((255.0 * 255.0) / mse)


def box_mean(arr: np.ndarray, win_size: int = 7) -> np.ndarray:
    pad = win_size // 2
    padded = np.pad(arr, pad_width=pad, mode="reflect")
    windows = np.lib.stride_tricks.sliding_window_view(padded, (win_size, win_size))
    return windows.mean(axis=(-1, -2))


def simple_ssim(a: np.ndarray, b: np.ndarray) -> float:
    """Windowed SSIM using NumPy only.

    This mirrors the default local-window SSIM used by common image metrics
    libraries closely enough for a dependency-light defense script.
    """
    a = a.astype(np.float64)
    b = b.astype(np.float64)
    if a.ndim == 3:
        return float(np.mean([simple_ssim(a[:, :, i], b[:, :, i]) for i in range(a.shape[2])]))
    win_size = 7
    pad = win_size // 2
    c1 = (0.01 * 255) ** 2
    c2 = (0.03 * 255) ** 2
    mu_a = box_mean(a, win_size)
    mu_b = box_mean(b, win_size)
    mu_a_sq = mu_a * mu_a
    mu_b_sq = mu_b * mu_b
    mu_ab = mu_a * mu_b
    cov_norm = (win_size * win_size) / (win_size * win_size - 1)
    var_a = cov_norm * (box_mean(a * a, win_size) - mu_a_sq)
    var_b = cov_norm * (box_mean(b * b, win_size) - mu_b_sq)
    cov_ab = cov_norm * (box_mean(a * b, win_size) - mu_ab)
    ssim_map = ((2 * mu_ab + c1) * (2 * cov_ab + c2)) / ((mu_a_sq + mu_b_sq + c1) * (var_a + var_b + c2))
    if min(ssim_map.shape) > 2 * pad:
        ssim_map = ssim_map[pad:-pad, pad:-pad]
    return float(np.mean(ssim_map))


def entropy(arr: np.ndarray) -> float:
    values, counts = np.unique(arr.astype(np.uint8), return_counts=True)
    probs = counts.astype(np.float64) / counts.sum()
    return float(-np.sum(probs * np.log2(probs + 1e-12)))


def finite_mean(values: list[float]) -> float:
    finite = [v for v in values if math.isfinite(v)]
    if not finite:
        return float("inf")
    return mean(finite)


def fmt_num(value: float, digits: int = 2) -> str:
    if math.isinf(value):
        return "inf"
    return f"{value:.{digits}f}"


def fmt_pair(left: str, right: str) -> str:
    return f"{left} / {right}"


def noise_cipher_like(reference: np.ndarray, seed: int = 20260524) -> np.ndarray:
    rng = np.random.default_rng(seed)
    return rng.integers(0, 256, size=reference.shape, dtype=np.uint8)


def lsb_embed(carrier_rgb: np.ndarray, secret_gray: np.ndarray) -> tuple[np.ndarray, int]:
    h = min(carrier_rgb.shape[0], secret_gray.shape[0])
    w = min(carrier_rgb.shape[1], secret_gray.shape[1])
    stego = carrier_rgb.copy()
    secret = secret_gray[:h, :w]
    bits = np.unpackbits(secret.reshape(-1, 1), axis=1)
    flat = stego[:h, :w, :].reshape(-1)
    capacity = flat.size
    payload = bits.reshape(-1)
    usable = min(capacity, payload.size)
    flat[:usable] = (flat[:usable] & 0xFE) | payload[:usable]
    stego[:h, :w, :] = flat.reshape(h, w, 3)
    return stego, usable


def lsb_extract(stego_rgb: np.ndarray, height: int, width: int) -> np.ndarray:
    h = min(stego_rgb.shape[0], height)
    w = min(stego_rgb.shape[1], width)
    bit_count = h * w * 8
    bits = (stego_rgb[:h, :w, :].reshape(-1) & 1)[:bit_count]
    if bits.size < bit_count:
        bits = np.pad(bits, (0, bit_count - bits.size))
    return np.packbits(bits.reshape(-1, 8), axis=1).reshape(h, w).astype(np.uint8)


def find_font(size: int):
    for candidate in ["C:/Windows/Fonts/msyh.ttc", "C:/Windows/Fonts/simhei.ttf", "C:/Windows/Fonts/arial.ttf"]:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def tile(path: Path, title: str, subtitle: str, size=(340, 260)) -> Image.Image:
    card_w, card_h = size
    canvas = Image.new("RGB", size, "#111827")
    draw = ImageDraw.Draw(canvas)
    draw.rounded_rectangle([0, 0, card_w - 1, card_h - 1], radius=14, outline="#334155", width=2, fill="#111827")
    img = Image.open(path).convert("RGB")
    preview = ImageOps.contain(img, (card_w - 42, card_h - 86), method=Image.Resampling.LANCZOS)
    canvas.paste(preview, ((card_w - preview.width) // 2, 62 + (card_h - 90 - preview.height) // 2))
    draw.text((18, 14), title, fill="#f8fafc", font=find_font(18))
    draw.text((18, 38), subtitle, fill="#9cc6e8", font=find_font(13))
    return canvas


def make_grid(output_dir: Path, items: list[tuple[str, str, Path]]) -> None:
    gap = 18
    cols = 3
    rows = math.ceil(len(items) / cols)
    grid_w = cols * 340 + (cols + 1) * gap
    grid_h = rows * 260 + (rows + 1) * gap + 42
    grid = Image.new("RGB", (grid_w, grid_h), "#0b1118")
    draw = ImageDraw.Draw(grid)
    draw.text((gap, 14), "Baseline Comparison: Ciphertext / LSB / AMP-CS", fill="#f8fafc", font=find_font(24))
    for idx, (title, subtitle, path) in enumerate(items):
        row, col = divmod(idx, cols)
        grid.paste(tile(path, title, subtitle), (gap + col * (340 + gap), 60 + row * (260 + gap)))
    grid.save(output_dir / "baseline_comparison_grid.png")


def write_rows(output_dir: Path, rows: list[dict], input_files: dict[str, list[str]]) -> None:
    fields = [
        "method",
        "comparison_role",
        "samples",
        "carrier_psnr",
        "carrier_ssim",
        "recovery_psnr",
        "recovery_ssim",
        "entropy",
        "reference",
        "notes",
    ]
    with (output_dir / "baseline_comparison.csv").open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    with (output_dir / "baseline_comparison.md").open("w", encoding="utf-8") as f:
        f.write("# Baseline comparison for AMP-CS demo\n\n")
        f.write("All rows use the same demo image set from `output/demo_experiments`.\n\n")
        f.write("## Input files\n\n")
        for label, files in input_files.items():
            f.write(f"- {label}: {', '.join(files)}\n")
        f.write("\n")
        f.write("## Metrics\n\n")
        f.write("| Method | Role | Samples | Carrier PSNR/SSIM | Recovery PSNR/SSIM | Entropy | Reference | Notes |\n")
        f.write("|---|---|---:|---:|---:|---:|---|---|\n")
        for r in rows:
            f.write(
                f"| {r['method']} | {r['comparison_role']} | {r['samples']} | "
                f"{fmt_pair(r['carrier_psnr'], r['carrier_ssim'])} | "
                f"{fmt_pair(r['recovery_psnr'], r['recovery_ssim'])} | {r['entropy']} | "
                f"{r['reference']} | {r['notes']} |\n"
            )
        f.write("\n")
        f.write("## PPT-ready conclusion\n\n")
        f.write(
            "- The noise-cipher row is a visual-appearance baseline, not a claim that AES can be broken. "
            "It explains why directly transmitted ciphertext is easy to notice.\n"
        )
        f.write(
            "- The LSB row is a classic single-image steganography baseline. It keeps the carrier almost unchanged. "
            "Recovery quality is not reported because this row is used only for carrier imperceptibility.\n"
        )
        f.write(
            "- The AMP-CS row has slightly stronger carrier disturbance than simple LSB, while still keeping high carrier "
            "similarity and providing correct-key recovery for all target images.\n"
        )
        f.write(
            "- The wrong-key ablation has very low recovery PSNR/SSIM, showing that the scrambling index and key are sensitive.\n"
        )


def run(input_dir: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    carrier = load_rgb(input_dir / "10_carrier_original.png")
    ampcs_stego = load_rgb(input_dir / "11_carrier_steganographic.png")
    target_paths = [input_dir / f"04_target_image_{idx}.png" for idx in range(1, 4)]
    ampcs_recovered_paths = [input_dir / f"recovered_B_target_{idx}.png" for idx in range(1, 4)]
    wrong_key_paths = [input_dir / f"wrong_key_target_{idx}.png" for idx in range(1, 4)]
    missing = [
        path
        for path in [input_dir / "10_carrier_original.png", input_dir / "11_carrier_steganographic.png"]
        + target_paths
        + ampcs_recovered_paths
        + wrong_key_paths
        if not path.exists()
    ]
    if missing:
        missing_text = "\n".join(str(path) for path in missing)
        raise FileNotFoundError(f"Missing demo artifacts:\n{missing_text}")

    targets = [load_gray(path) for path in target_paths]
    ampcs_recovered = [load_gray(path) for path in ampcs_recovered_paths]
    wrong_keys = [load_gray(path) for path in wrong_key_paths]

    noise_outputs = [noise_cipher_like(target, seed=20260524 + idx) for idx, target in enumerate(targets)]
    noise = noise_outputs[0]
    noise_rgb = np.repeat(noise[:, :, None], 3, axis=2)
    save_rgb(output_dir / "baseline_noise_cipher.png", noise_rgb)

    lsb_stegos = []
    lsb_recovered = []
    lsb_bits = []
    for target in targets:
        stego, bits = lsb_embed(carrier, target)
        recovered = lsb_extract(stego, target.shape[0], target.shape[1])
        lsb_stegos.append(stego)
        lsb_recovered.append(recovered)
        lsb_bits.append(bits)
    save_rgb(output_dir / "baseline_lsb_stego.png", lsb_stegos[0])
    Image.fromarray(lsb_recovered[0]).save(output_dir / "baseline_lsb_recovered.png")

    save_rgb(output_dir / "ampcs_stego.png", ampcs_stego)
    Image.fromarray(ampcs_recovered[0]).save(output_dir / "ampcs_recovered_target.png")
    Image.fromarray(wrong_keys[0]).save(output_dir / "ampcs_wrong_key.png")

    noise_recovery_psnr = finite_mean([psnr(target, noise) for target, noise in zip(targets, noise_outputs)])
    noise_recovery_ssim = mean([simple_ssim(target, noise) for target, noise in zip(targets, noise_outputs)])
    noise_entropy = mean([entropy(noise) for noise in noise_outputs])

    lsb_carrier_psnr = finite_mean([psnr(carrier, stego) for stego in lsb_stegos])
    lsb_carrier_ssim = mean([simple_ssim(carrier, stego) for stego in lsb_stegos])
    lsb_recovery_psnr = finite_mean([psnr(target, recovered) for target, recovered in zip(targets, lsb_recovered)])
    lsb_recovery_ssim = mean([simple_ssim(target, recovered) for target, recovered in zip(targets, lsb_recovered)])
    lsb_entropy = mean([entropy(stego) for stego in lsb_stegos])

    ampcs_recovery_psnr = finite_mean([psnr(target, recovered) for target, recovered in zip(targets, ampcs_recovered)])
    ampcs_recovery_ssim = mean([simple_ssim(target, recovered) for target, recovered in zip(targets, ampcs_recovered)])
    wrong_key_psnr = finite_mean([psnr(target, wrong_key) for target, wrong_key in zip(targets, wrong_keys)])
    wrong_key_ssim = mean([simple_ssim(target, wrong_key) for target, wrong_key in zip(targets, wrong_keys)])
    wrong_key_entropy = mean([entropy(wrong_key) for wrong_key in wrong_keys])

    rows = [
        {
            "method": "Noise-cipher baseline",
            "comparison_role": "traditional ciphertext appearance",
            "samples": "3 target images",
            "carrier_psnr": "-",
            "carrier_ssim": "-",
            "recovery_psnr": fmt_num(noise_recovery_psnr, 2),
            "recovery_ssim": fmt_num(noise_recovery_ssim, 4),
            "entropy": fmt_num(noise_entropy, 2),
            "reference": "NIST FIPS 197 (AES); used here only as ciphertext-appearance baseline",
            "notes": "Shows why visible ciphertext attracts attention; not a cryptographic-strength comparison.",
        },
        {
            "method": "LSB steganography baseline",
            "comparison_role": "ordinary single-image steganography",
            "samples": "3 target images, evaluated one by one",
            "carrier_psnr": fmt_num(lsb_carrier_psnr, 2),
            "carrier_ssim": fmt_num(lsb_carrier_ssim, 4),
            "recovery_psnr": "-",
            "recovery_ssim": "-",
            "entropy": fmt_num(lsb_entropy, 2),
            "reference": "Chan and Cheng, Pattern Recognition, 2004",
            "notes": f"Mean carrier imperceptibility over simple LSB payload tests; each test embeds {min(lsb_bits)} bits and has no multi-level permission design.",
        },
        {
            "method": "AMP-CS system",
            "comparison_role": "compressed measurement + DCT stego + role recovery",
            "samples": "3 target images",
            "carrier_psnr": fmt_num(psnr(carrier, ampcs_stego), 2),
            "carrier_ssim": fmt_num(simple_ssim(carrier, ampcs_stego), 4),
            "recovery_psnr": fmt_num(ampcs_recovery_psnr, 2),
            "recovery_ssim": fmt_num(ampcs_recovery_ssim, 4),
            "entropy": fmt_num(entropy(ampcs_stego), 2),
            "reference": "Candes et al., 2006; Donoho, 2006; project AMP-CS implementation",
            "notes": "Supports carrier preview, target/source recovery, and wrong-key failure.",
        },
        {
            "method": "AMP-CS wrong-key ablation",
            "comparison_role": "key sensitivity",
            "samples": "3 target images",
            "carrier_psnr": "-",
            "carrier_ssim": "-",
            "recovery_psnr": fmt_num(wrong_key_psnr, 2),
            "recovery_ssim": fmt_num(wrong_key_ssim, 4),
            "entropy": fmt_num(wrong_key_entropy, 2),
            "reference": "Project ablation experiment",
            "notes": "Wrong scrambling index fails to recover valid target image.",
        },
    ]
    input_files = {
        "carrier": ["10_carrier_original.png", "11_carrier_steganographic.png"],
        "targets": [path.name for path in target_paths],
        "AMP-CS correct recovery": [path.name for path in ampcs_recovered_paths],
        "AMP-CS wrong-key recovery": [path.name for path in wrong_key_paths],
    }
    write_rows(output_dir, rows, input_files)

    make_grid(
        output_dir,
        [
            ("Original carrier", "public-looking image", input_dir / "10_carrier_original.png"),
            ("Noise cipher baseline", "visible ciphertext appearance", output_dir / "baseline_noise_cipher.png"),
            ("LSB stego baseline", "ordinary steganography", output_dir / "baseline_lsb_stego.png"),
            ("AMP-CS output", "compressed measurement stego", output_dir / "ampcs_stego.png"),
            ("AMP-CS recovery", "correct key restores target", output_dir / "ampcs_recovered_target.png"),
            ("Wrong-key recovery", "key/index error fails", output_dir / "ampcs_wrong_key.png"),
        ],
    )
    print(f"Saved baseline artifacts to: {output_dir}")
    print(output_dir / "baseline_comparison_grid.png")
    print(output_dir / "baseline_comparison.csv")
    print(output_dir / "baseline_comparison.md")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate baseline comparison artifacts.")
    parser.add_argument("--input-dir", default=str(ROOT / "output" / "demo_experiments"))
    parser.add_argument("--output-dir", default=str(ROOT / "output" / "baseline_comparison"))
    args = parser.parse_args()
    run(Path(args.input_dir).resolve(), Path(args.output_dir).resolve())


if __name__ == "__main__":
    main()
