"""
Compare traditional CS reconstruction baselines with the AMP-CS demo output.

The script keeps dependencies to NumPy + Pillow. It reads the same MATLAB v5
sampling matrix used by AMP-Net, generates measurements from the same target
images, and compares:

- SPL-style projected Landweber reconstruction with DCT thresholding.
- OMP-DCT sparse reconstruction.
- AMP-Net output already generated by run_demo_experiments.py.
"""

import argparse
import csv
import math
import struct
import time
from pathlib import Path
from statistics import mean

import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageOps


ROOT = Path(__file__).resolve().parent
BLOCK_SIZE = 33


def load_gray(path: Path) -> np.ndarray:
    return np.array(Image.open(path).convert("L"), dtype=np.float64)


def save_gray(path: Path, arr: np.ndarray) -> None:
    Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8)).save(path)


def read_mat_v5_matrix(path: Path, variable_name: str) -> np.ndarray:
    data = path.read_bytes()
    endian = "<" if data[126:128] == b"IM" else ">"
    pos = 128

    def align8(value: int) -> int:
        return value + ((8 - value % 8) % 8)

    def read_element(offset: int):
        tag0, tag1 = struct.unpack_from(endian + "II", data, offset)
        if tag0 >> 16:
            dtype = tag0 & 0xFFFF
            size = tag0 >> 16
            payload = data[offset + 4 : offset + 4 + size]
            return dtype, payload, offset + 8
        dtype = tag0
        size = tag1
        start = offset + 8
        end = start + size
        return dtype, data[start:end], align8(end)

    while pos < len(data):
        dtype, payload, pos = read_element(pos)
        if dtype != 14:
            continue

        inner = 0
        dims = None
        name = None
        values = None
        value_dtype = None
        while inner < len(payload):
            sub_type, sub_payload, next_inner = None, None, None
            tag0, tag1 = struct.unpack_from(endian + "II", payload, inner)
            if tag0 >> 16:
                sub_type = tag0 & 0xFFFF
                sub_size = tag0 >> 16
                sub_payload = payload[inner + 4 : inner + 4 + sub_size]
                next_inner = inner + 8
            else:
                sub_type = tag0
                sub_size = tag1
                start = inner + 8
                end = start + sub_size
                sub_payload = payload[start:end]
                next_inner = align8(end)

            if sub_type == 5:
                dims = tuple(np.frombuffer(sub_payload, dtype=endian + "i4").tolist())
            elif sub_type == 1:
                name = sub_payload.decode("utf-8", errors="ignore").rstrip("\x00")
            elif sub_type in (7, 9):
                value_dtype = sub_type
                values = sub_payload
            inner = next_inner

        if name != variable_name or dims is None or values is None:
            continue

        dtype_np = endian + ("f4" if value_dtype == 7 else "f8")
        return np.frombuffer(values, dtype=dtype_np).reshape(dims, order="F").astype(np.float32)

    raise KeyError(f"Variable {variable_name!r} not found in {path}")


def pad_image(image: np.ndarray, block_size: int = BLOCK_SIZE):
    row, col = image.shape
    row_pad = (block_size - row % block_size) % block_size
    col_pad = (block_size - col % block_size) % block_size
    padded = np.pad(image, ((0, row_pad), (0, col_pad)), mode="constant")
    return padded, padded.shape[0], padded.shape[1]


def image_to_blocks(image: np.ndarray, block_size: int = BLOCK_SIZE):
    padded, row_new, col_new = pad_image(image, block_size)
    block_rows = row_new // block_size
    block_cols = col_new // block_size
    inputs = np.expand_dims((padded / 255.0).astype(np.float32), axis=0)
    inputs = np.concatenate(np.split(inputs, block_rows, axis=1), axis=0)
    inputs = np.concatenate(np.split(inputs, block_cols, axis=2), axis=0)
    blocks = np.transpose(np.reshape(inputs, [-1, block_size * block_size]), (1, 0)).astype(np.float32)
    return blocks, row_new, col_new, block_rows, block_cols


def blocks_to_image(blocks: np.ndarray, height: int, width: int, row_new: int, col_new: int, block_size: int = BLOCK_SIZE) -> np.ndarray:
    image = np.zeros([row_new, col_new], dtype=np.float32)
    count = 0
    for y in range(0, col_new - block_size + 1, block_size):
        for x in range(0, row_new - block_size + 1, block_size):
            image[x : x + block_size, y : y + block_size] = blocks[:, count].reshape([block_size, block_size])
            count += 1
    return np.clip(image[:height, :width] * 255.0, 0, 255)


def dct_matrix(size: int) -> np.ndarray:
    n = np.arange(size)
    k = n[:, None]
    mat = np.cos(np.pi * (n + 0.5) * k / size)
    mat[0, :] *= math.sqrt(1.0 / size)
    mat[1:, :] *= math.sqrt(2.0 / size)
    return mat.astype(np.float32)


def dct_blocks(blocks: np.ndarray, dct: np.ndarray) -> np.ndarray:
    shaped = blocks.T.reshape(-1, BLOCK_SIZE, BLOCK_SIZE)
    coeff = np.matmul(np.matmul(dct[None, :, :], shaped), dct.T[None, :, :])
    return coeff.reshape(-1, BLOCK_SIZE * BLOCK_SIZE).T


def idct_blocks(coeffs: np.ndarray, dct: np.ndarray) -> np.ndarray:
    shaped = coeffs.T.reshape(-1, BLOCK_SIZE, BLOCK_SIZE)
    blocks = np.matmul(np.matmul(dct.T[None, :, :], shaped), dct[None, :, :])
    return blocks.reshape(-1, BLOCK_SIZE * BLOCK_SIZE).T


def keep_top_coefficients(coeffs: np.ndarray, keep: int) -> np.ndarray:
    keep = max(1, min(keep, coeffs.shape[0]))
    out = np.zeros_like(coeffs)
    if keep == coeffs.shape[0]:
        return coeffs
    idx = np.argpartition(np.abs(coeffs), -keep, axis=0)[-keep:, :]
    cols = np.arange(coeffs.shape[1])[None, :]
    out[idx, cols] = coeffs[idx, cols]
    return out


def reconstruct_spl(measurements: np.ndarray, sampling_matrix: np.ndarray, dct: np.ndarray, iterations: int, keep_start: int, keep_end: int) -> np.ndarray:
    spectral_norm = np.linalg.norm(sampling_matrix, ord=2)
    step = 1.0 / (spectral_norm * spectral_norm + 1e-8)
    x = sampling_matrix.T @ measurements
    for i in range(iterations):
        residual = measurements - sampling_matrix @ x
        x = x + step * (sampling_matrix.T @ residual)
        keep = round(keep_start + (keep_end - keep_start) * (i / max(1, iterations - 1)))
        coeff = keep_top_coefficients(dct_blocks(x, dct), keep)
        x = idct_blocks(coeff, dct)
        x = np.clip(x, 0.0, 1.0)
    return x.astype(np.float32)


def build_idct_dictionary(dct: np.ndarray) -> np.ndarray:
    return np.kron(dct.T, dct.T).astype(np.float32)


def reconstruct_omp(measurements: np.ndarray, sampling_matrix: np.ndarray, idct_dictionary: np.ndarray, max_atoms: int, tolerance: float) -> np.ndarray:
    dictionary = sampling_matrix @ idct_dictionary
    norms = np.linalg.norm(dictionary, axis=0) + 1e-8
    dictionary_normed = dictionary / norms
    reconstructed = np.zeros((idct_dictionary.shape[0], measurements.shape[1]), dtype=np.float32)

    for col in range(measurements.shape[1]):
        y = measurements[:, col]
        residual = y.copy()
        support: list[int] = []
        alpha = None
        target_norm = np.linalg.norm(y) + 1e-8
        for _ in range(max_atoms):
            correlations = dictionary_normed.T @ residual
            idx = int(np.argmax(np.abs(correlations)))
            if idx in support:
                break
            support.append(idx)
            sub_dict = dictionary_normed[:, support]
            alpha, *_ = np.linalg.lstsq(sub_dict, y, rcond=None)
            residual = y - sub_dict @ alpha
            if np.linalg.norm(residual) / target_norm < tolerance:
                break
        if support and alpha is not None:
            coeff = np.zeros(idct_dictionary.shape[1], dtype=np.float32)
            coeff[np.array(support)] = (alpha / norms[np.array(support)]).astype(np.float32)
            reconstructed[:, col] = idct_dictionary @ coeff
        else:
            reconstructed[:, col] = sampling_matrix.T @ y
    return np.clip(reconstructed, 0.0, 1.0)


def psnr(a: np.ndarray, b: np.ndarray) -> float:
    a = a.astype(np.float64)
    b = b.astype(np.float64)
    mse = np.mean((a - b) ** 2)
    if mse == 0:
        return float("inf")
    return 10 * math.log10((255.0 * 255.0) / mse)


def box_mean(arr: np.ndarray, win_size: int = 7) -> np.ndarray:
    pad = win_size // 2
    padded = np.pad(arr, pad_width=pad, mode="reflect")
    windows = np.lib.stride_tricks.sliding_window_view(padded, (win_size, win_size))
    return windows.mean(axis=(-1, -2))


def ssim(a: np.ndarray, b: np.ndarray) -> float:
    a = a.astype(np.float64)
    b = b.astype(np.float64)
    win_size = 7
    pad = win_size // 2
    c1 = (0.01 * 255) ** 2
    c2 = (0.03 * 255) ** 2
    mu_a = box_mean(a, win_size)
    mu_b = box_mean(b, win_size)
    mu_a_sq = mu_a * mu_a
    mu_b_sq = mu_b * mu_b
    mu_ab = mu_a * mu_b
    cov_norm = (win_size * win_size) / (win_size * win_size - 1)
    var_a = cov_norm * (box_mean(a * a, win_size) - mu_a_sq)
    var_b = cov_norm * (box_mean(b * b, win_size) - mu_b_sq)
    cov_ab = cov_norm * (box_mean(a * b, win_size) - mu_ab)
    ssim_map = ((2 * mu_ab + c1) * (2 * cov_ab + c2)) / ((mu_a_sq + mu_b_sq + c1) * (var_a + var_b + c2))
    if min(ssim_map.shape) > 2 * pad:
        ssim_map = ssim_map[pad:-pad, pad:-pad]
    return float(np.mean(ssim_map))


def avg_metric(items: list[dict], key: str) -> float:
    values = [item[key] for item in items if math.isfinite(item[key])]
    return mean(values) if values else float("nan")


def read_amp_time(summary_csv: Path) -> float | None:
    if not summary_csv.exists():
        return None
    with summary_csv.open("r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            if row.get("实验项") == "运行效率":
                parts = row.get("结果", "").split("/")
                if len(parts) >= 3:
                    value = parts[2].strip().lower().replace("s", "")
                    try:
                        return float(value)
                    except ValueError:
                        return None
    return None


def find_font(size: int):
    for candidate in ["C:/Windows/Fonts/msyh.ttc", "C:/Windows/Fonts/simhei.ttf", "C:/Windows/Fonts/arial.ttf"]:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def tile(path: Path, title: str, subtitle: str, size=(280, 230)) -> Image.Image:
    card_w, card_h = size
    canvas = Image.new("RGB", size, "#111827")
    draw = ImageDraw.Draw(canvas)
    draw.rounded_rectangle([0, 0, card_w - 1, card_h - 1], radius=10, outline="#334155", width=2, fill="#111827")
    img = Image.open(path).convert("RGB")
    preview = ImageOps.contain(img, (card_w - 38, card_h - 78), method=Image.Resampling.LANCZOS)
    canvas.paste(preview, ((card_w - preview.width) // 2, 58 + (card_h - 88 - preview.height) // 2))
    draw.text((16, 12), title, fill="#f8fafc", font=find_font(16))
    draw.text((16, 35), subtitle, fill="#9cc6e8", font=find_font(12))
    return canvas


def make_grid(output_dir: Path, target_paths: list[Path], method_dirs: dict[str, Path]) -> None:
    gap = 14
    cols = 4
    rows = len(target_paths)
    grid_w = cols * 280 + (cols + 1) * gap
    grid_h = rows * 230 + (rows + 1) * gap + 42
    grid = Image.new("RGB", (grid_w, grid_h), "#0b1118")
    draw = ImageDraw.Draw(grid)
    draw.text((gap, 12), "Reconstruction Baselines: SPL / OMP / AMP-Net", fill="#f8fafc", font=find_font(22))
    for row_idx, target_path in enumerate(target_paths):
        items = [
            ("Original", f"target {row_idx + 1}", target_path),
            ("SPL-style", "iterative CS", method_dirs["SPL-style"] / f"spl_recovered_{row_idx + 1}.png"),
            ("OMP-DCT", "sparse baseline", method_dirs["OMP-DCT"] / f"omp_recovered_{row_idx + 1}.png"),
            ("AMP-Net", "project output", method_dirs["AMP-Net"] / f"amp_recovered_{row_idx + 1}.png"),
        ]
        for col_idx, (title, subtitle, path) in enumerate(items):
            grid.paste(tile(path, title, subtitle), (gap + col_idx * (280 + gap), 54 + row_idx * (230 + gap)))
    grid.save(output_dir / "reconstruction_comparison_grid.png")


def write_outputs(output_dir: Path, rows: list[dict], target_names: list[str], sampling_matrix_name: str) -> None:
    fields = ["method", "condition", "total_time_s", "avg_time_s", "psnr", "ssim", "reference", "notes"]
    with (output_dir / "reconstruction_comparison.csv").open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    with (output_dir / "reconstruction_comparison.md").open("w", encoding="utf-8") as f:
        f.write("# SPL / OMP / AMP-Net reconstruction comparison\n\n")
        f.write(f"- Target images: {', '.join(target_names)}\n")
        f.write(f"- Sampling matrix: `{sampling_matrix_name}`\n")
        f.write("- Compression ratio: 60%, block size: 33 x 33\n\n")
        f.write("| Method | Condition | Total time | Avg time/image | PSNR | SSIM | Reference | Notes |\n")
        f.write("|---|---|---:|---:|---:|---:|---|---|\n")
        for row in rows:
            f.write(
                f"| {row['method']} | {row['condition']} | {row['total_time_s']}s | {row['avg_time_s']}s | "
                f"{row['psnr']} | {row['ssim']} | {row['reference']} | {row['notes']} |\n"
            )


def run(input_dir: Path, output_dir: Path, sampling_matrix_path: Path, spl_iterations: int, omp_atoms: int) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    sampling_matrix = read_mat_v5_matrix(sampling_matrix_path, "sampling_matrix")
    dct = dct_matrix(BLOCK_SIZE)
    idct_dictionary = build_idct_dictionary(dct)

    target_paths = [input_dir / f"04_target_image_{idx}.png" for idx in range(1, 4)]
    amp_paths = [input_dir / f"recovered_B_target_{idx}.png" for idx in range(1, 4)]
    missing = [path for path in [*target_paths, *amp_paths, sampling_matrix_path] if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing files:\n" + "\n".join(str(path) for path in missing))

    target_images = [load_gray(path) for path in target_paths]
    block_meta = [image_to_blocks(image) for image in target_images]
    measurements = [sampling_matrix @ meta[0] for meta in block_meta]

    rows = []
    method_dirs = {
        "SPL-style": output_dir / "spl",
        "OMP-DCT": output_dir / "omp",
        "AMP-Net": output_dir / "amp",
    }
    for path in method_dirs.values():
        path.mkdir(parents=True, exist_ok=True)

    spl_metrics = []
    spl_start = time.perf_counter()
    for idx, (image, meta, y) in enumerate(zip(target_images, block_meta, measurements), start=1):
        _, row_new, col_new, _, _ = meta
        recovered_blocks = reconstruct_spl(
            y,
            sampling_matrix,
            dct,
            iterations=spl_iterations,
            keep_start=520,
            keep_end=240,
        )
        recovered = blocks_to_image(recovered_blocks, image.shape[0], image.shape[1], row_new, col_new)
        save_gray(method_dirs["SPL-style"] / f"spl_recovered_{idx}.png", recovered)
        spl_metrics.append({"psnr": psnr(image, recovered), "ssim": ssim(image, recovered)})
    spl_total = time.perf_counter() - spl_start
    rows.append(
        {
            "method": "SPL-style",
            "condition": f"{spl_iterations} iterations, DCT thresholding",
            "total_time_s": f"{spl_total:.2f}",
            "avg_time_s": f"{spl_total / len(target_images):.2f}",
            "psnr": f"{avg_metric(spl_metrics, 'psnr'):.2f}",
            "ssim": f"{avg_metric(spl_metrics, 'ssim'):.4f}",
            "reference": "Smoothed Projected Landweber CS reconstruction",
            "notes": "Traditional iterative CS baseline under the same sampling matrix.",
        }
    )

    omp_metrics = []
    omp_start = time.perf_counter()
    for idx, (image, meta, y) in enumerate(zip(target_images, block_meta, measurements), start=1):
        _, row_new, col_new, _, _ = meta
        recovered_blocks = reconstruct_omp(
            y,
            sampling_matrix,
            idct_dictionary,
            max_atoms=omp_atoms,
            tolerance=1e-3,
        )
        recovered = blocks_to_image(recovered_blocks, image.shape[0], image.shape[1], row_new, col_new)
        save_gray(method_dirs["OMP-DCT"] / f"omp_recovered_{idx}.png", recovered)
        omp_metrics.append({"psnr": psnr(image, recovered), "ssim": ssim(image, recovered)})
    omp_total = time.perf_counter() - omp_start
    rows.append(
        {
            "method": "OMP-DCT",
            "condition": f"max {omp_atoms} atoms/block, DCT sparse basis",
            "total_time_s": f"{omp_total:.2f}",
            "avg_time_s": f"{omp_total / len(target_images):.2f}",
            "psnr": f"{avg_metric(omp_metrics, 'psnr'):.2f}",
            "ssim": f"{avg_metric(omp_metrics, 'ssim'):.4f}",
            "reference": "Orthogonal Matching Pursuit sparse recovery",
            "notes": "Classic sparse reconstruction baseline; computationally heavier per block.",
        }
    )

    amp_metrics = []
    for idx, (image, path) in enumerate(zip(target_images, amp_paths), start=1):
        recovered = load_gray(path)
        save_gray(method_dirs["AMP-Net"] / f"amp_recovered_{idx}.png", recovered)
        amp_metrics.append({"psnr": psnr(image, recovered), "ssim": ssim(image, recovered)})
    amp_total = read_amp_time(input_dir / "experiment_summary.csv")
    amp_total = amp_total if amp_total is not None else float("nan")
    rows.append(
        {
            "method": "AMP-Net",
            "condition": "project model output, 9 phases",
            "total_time_s": f"{amp_total:.2f}" if math.isfinite(amp_total) else "-",
            "avg_time_s": f"{amp_total / len(target_images):.2f}" if math.isfinite(amp_total) else "-",
            "psnr": f"{avg_metric(amp_metrics, 'psnr'):.2f}",
            "ssim": f"{avg_metric(amp_metrics, 'ssim'):.4f}",
            "reference": "Project AMP-Net implementation",
            "notes": "Uses the recovered_B_target images generated by the existing demo.",
        }
    )

    write_outputs(output_dir, rows, [path.name for path in target_paths], sampling_matrix_path.name)
    make_grid(output_dir, target_paths, method_dirs)
    print(f"Saved reconstruction baseline artifacts to: {output_dir}")
    print(output_dir / "reconstruction_comparison.md")
    print(output_dir / "reconstruction_comparison_grid.png")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run SPL/OMP reconstruction baselines against AMP-Net demo output.")
    parser.add_argument("--input-dir", default=str(ROOT / "output" / "demo_experiments"))
    parser.add_argument("--output-dir", default=str(ROOT / "output" / "reconstruction_baselines"))
    parser.add_argument("--sampling-matrix", default=str(ROOT / "dataset" / "sampling_matrix" / "60.mat"))
    parser.add_argument("--spl-iterations", type=int, default=80)
    parser.add_argument("--omp-atoms", type=int, default=60)
    args = parser.parse_args()
    run(
        Path(args.input_dir).resolve(),
        Path(args.output_dir).resolve(),
        Path(args.sampling_matrix).resolve(),
        args.spl_iterations,
        args.omp_atoms,
    )


if __name__ == "__main__":
    main()
